package dambi.accessingrelationaldata;

import java.util.List;
import java.util.Optional;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springdoc.core.RequestBodyInfo;
import org.springframework.*;

import io.swagger.v3.oas.annotations.parameters.RequestBody;

@RestController // This means that this class is a Controller
@RequestMapping(path = "/jatetxeak") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private JatetxeaRepository jatetxeaRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody String berria(@RequestParam String name, @RequestParam String mota, @RequestParam List<Helbidea> helbidea) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Jatetxea j = new Jatetxea();
        j.setIzena(name);
        j.setMota(mota);
		j.setHelbidea(helbidea);
        jatetxeaRepository.save(j);
        return "Saved";
    }

    @GetMapping(path = "/danak")
    public @ResponseBody Iterable<Jatetxea> danak() {
        // This returns a JSON or XML with the users
        return jatetxeaRepository.findAll();
    }

}